export interface Technology {
  id: string;
  name: string;
  icon: string;
  category: TechCategory;
  color?: string;
}

export type TechCategory =
  | "language"
  | "frontend"
  | "backend"
  | "database"
  | "devops"
  | "mobile"
  | "testing"
  | "design"
  | "ai"
  | "other";

export const TECH_CATEGORIES: Record<
  TechCategory,
  { label: string; color: string }
> = {
  language: { label: "Linguagens", color: "#3b82f6" },
  frontend: { label: "Frontend", color: "#8b5cf6" },
  backend: { label: "Backend", color: "#10b981" },
  database: { label: "Banco de Dados", color: "#f59e0b" },
  devops: { label: "DevOps & Cloud", color: "#ec4899" },
  mobile: { label: "Mobile", color: "#06b6d4" },
  testing: { label: "Testes", color: "#84cc16" },
  design: { label: "Design", color: "#f43f5e" },
  ai: { label: "AI & ML", color: "#a855f7" },
  other: { label: "Outros", color: "#6b7280" },
};

export const TECHNOLOGIES: Technology[] = [
  {
    id: "typescript",
    name: "TypeScript",
    icon: "SiTypescript",
    category: "language",
    color: "#3178c6",
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "SiJavascript",
    category: "language",
    color: "#f7df1e",
  },
  {
    id: "python",
    name: "Python",
    icon: "SiPython",
    category: "language",
    color: "#3776ab",
  },
  {
    id: "rust",
    name: "Rust",
    icon: "SiRust",
    category: "language",
    color: "#000000",
  },
  {
    id: "go",
    name: "Go",
    icon: "SiGo",
    category: "language",
    color: "#00add8",
  },
  {
    id: "java",
    name: "Java",
    icon: "FaJava",
    category: "language",
    color: "#007396",
  },
  {
    id: "csharp",
    name: "C#",
    icon: "SiCsharp",
    category: "language",
    color: "#239120",
  },
  {
    id: "cpp",
    name: "C++",
    icon: "SiCplusplus",
    category: "language",
    color: "#00599c",
  },
  {
    id: "php",
    name: "PHP",
    icon: "SiPhp",
    category: "language",
    color: "#777bb4",
  },
  {
    id: "ruby",
    name: "Ruby",
    icon: "SiRuby",
    category: "language",
    color: "#cc342d",
  },
  {
    id: "swift",
    name: "Swift",
    icon: "SiSwift",
    category: "language",
    color: "#fa7343",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    icon: "SiKotlin",
    category: "language",
    color: "#7f52ff",
  },

  {
    id: "react",
    name: "React",
    icon: "SiReact",
    category: "frontend",
    color: "#61dafb",
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "SiNextdotjs",
    category: "frontend",
    color: "#000000",
  },
  {
    id: "vue",
    name: "Vue.js",
    icon: "SiVuedotjs",
    category: "frontend",
    color: "#4fc08d",
  },
  {
    id: "nuxt",
    name: "Nuxt",
    icon: "SiNuxtdotjs",
    category: "frontend",
    color: "#00dc82",
  },
  {
    id: "angular",
    name: "Angular",
    icon: "SiAngular",
    category: "frontend",
    color: "#dd0031",
  },
  {
    id: "svelte",
    name: "Svelte",
    icon: "SiSvelte",
    category: "frontend",
    color: "#ff3e00",
  },
  {
    id: "astro",
    name: "Astro",
    icon: "SiAstro",
    category: "frontend",
    color: "#ff5d01",
  },
  {
    id: "remix",
    name: "Remix",
    icon: "SiRemix",
    category: "frontend",
    color: "#000000",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    icon: "SiTailwindcss",
    category: "frontend",
    color: "#06b6d4",
  },
  {
    id: "sass",
    name: "Sass",
    icon: "SiSass",
    category: "frontend",
    color: "#cc6699",
  },
  {
    id: "css",
    name: "CSS",
    icon: "SiCss3",
    category: "frontend",
    color: "#1572b6",
  },
  {
    id: "html",
    name: "HTML",
    icon: "SiHtml5",
    category: "frontend",
    color: "#e34f26",
  },
  {
    id: "redux",
    name: "Redux",
    icon: "SiRedux",
    category: "frontend",
    color: "#764abc",
  },
  {
    id: "zustand",
    name: "Zustand",
    icon: "SiReact",
    category: "frontend",
    color: "#443e38",
  },
  {
    id: "framer-motion",
    name: "Framer Motion",
    icon: "SiFramer",
    category: "frontend",
    color: "#0055ff",
  },
  {
    id: "gsap",
    name: "GSAP",
    icon: "SiGreensock",
    category: "frontend",
    color: "#88ce02",
  },
  {
    id: "threejs",
    name: "Three.js",
    icon: "SiThreedotjs",
    category: "frontend",
    color: "#000000",
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    icon: "SiShadcnui",
    category: "frontend",
    color: "#000000",
  },
  {
    id: "radix",
    name: "Radix UI",
    icon: "SiRadixui",
    category: "frontend",
    color: "#161618",
  },
  {
    id: "chakra",
    name: "Chakra UI",
    icon: "SiChakraui",
    category: "frontend",
    color: "#319795",
  },
  {
    id: "mui",
    name: "Material UI",
    icon: "SiMui",
    category: "frontend",
    color: "#007fff",
  },
  {
    id: "antd",
    name: "Ant Design",
    icon: "SiAntdesign",
    category: "frontend",
    color: "#0170fe",
  },
  {
    id: "storybook",
    name: "Storybook",
    icon: "SiStorybook",
    category: "frontend",
    color: "#ff4785",
  },

  {
    id: "nodejs",
    name: "Node.js",
    icon: "SiNodedotjs",
    category: "backend",
    color: "#339933",
  },
  {
    id: "express",
    name: "Express",
    icon: "SiExpress",
    category: "backend",
    color: "#000000",
  },
  {
    id: "fastify",
    name: "Fastify",
    icon: "SiFastify",
    category: "backend",
    color: "#000000",
  },
  {
    id: "nestjs",
    name: "NestJS",
    icon: "SiNestjs",
    category: "backend",
    color: "#e0234e",
  },
  {
    id: "django",
    name: "Django",
    icon: "SiDjango",
    category: "backend",
    color: "#092e20",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: "SiFastapi",
    category: "backend",
    color: "#009688",
  },
  {
    id: "flask",
    name: "Flask",
    icon: "SiFlask",
    category: "backend",
    color: "#000000",
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    icon: "SiRubyonrails",
    category: "backend",
    color: "#cc0000",
  },
  {
    id: "laravel",
    name: "Laravel",
    icon: "SiLaravel",
    category: "backend",
    color: "#ff2d20",
  },
  {
    id: "dotnet",
    name: ".NET",
    icon: "SiDotnet",
    category: "backend",
    color: "#512bd4",
  },
  {
    id: "spring",
    name: "Spring",
    icon: "SiSpring",
    category: "backend",
    color: "#6db33f",
  },
  {
    id: "graphql",
    name: "GraphQL",
    icon: "SiGraphql",
    category: "backend",
    color: "#e10098",
  },
  {
    id: "trpc",
    name: "tRPC",
    icon: "SiTrpc",
    category: "backend",
    color: "#2596be",
  },
  {
    id: "prisma",
    name: "Prisma",
    icon: "SiPrisma",
    category: "backend",
    color: "#2d3748",
  },
  {
    id: "drizzle",
    name: "Drizzle",
    icon: "SiDrizzle",
    category: "backend",
    color: "#c5f74f",
  },
  {
    id: "socketio",
    name: "Socket.io",
    icon: "SiSocketdotio",
    category: "backend",
    color: "#010101",
  },

  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "SiPostgresql",
    category: "database",
    color: "#4169e1",
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: "SiMysql",
    category: "database",
    color: "#4479a1",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    icon: "SiMongodb",
    category: "database",
    color: "#47a248",
  },
  {
    id: "redis",
    name: "Redis",
    icon: "SiRedis",
    category: "database",
    color: "#dc382d",
  },
  {
    id: "sqlite",
    name: "SQLite",
    icon: "SiSqlite",
    category: "database",
    color: "#003b57",
  },
  {
    id: "supabase",
    name: "Supabase",
    icon: "SiSupabase",
    category: "database",
    color: "#3fcf8e",
  },
  {
    id: "firebase",
    name: "Firebase",
    icon: "SiFirebase",
    category: "database",
    color: "#ffca28",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    icon: "SiPlanetscale",
    category: "database",
    color: "#000000",
  },
  {
    id: "neon",
    name: "Neon",
    icon: "SiNeon",
    category: "database",
    color: "#00e599",
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    icon: "SiElasticsearch",
    category: "database",
    color: "#005571",
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    icon: "SiAmazondynamodb",
    category: "database",
    color: "#4053d6",
  },

  {
    id: "docker",
    name: "Docker",
    icon: "SiDocker",
    category: "devops",
    color: "#2496ed",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    icon: "SiKubernetes",
    category: "devops",
    color: "#326ce5",
  },
  {
    id: "aws",
    name: "AWS",
    icon: "SiAmazonwebservices",
    category: "devops",
    color: "#ff9900",
  },
  {
    id: "gcp",
    name: "Google Cloud",
    icon: "SiGooglecloud",
    category: "devops",
    color: "#4285f4",
  },
  {
    id: "azure",
    name: "Azure",
    icon: "SiMicrosoftazure",
    category: "devops",
    color: "#0078d4",
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: "SiVercel",
    category: "devops",
    color: "#000000",
  },
  {
    id: "netlify",
    name: "Netlify",
    icon: "SiNetlify",
    category: "devops",
    color: "#00c7b7",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    icon: "SiCloudflare",
    category: "devops",
    color: "#f38020",
  },
  {
    id: "railway",
    name: "Railway",
    icon: "SiRailway",
    category: "devops",
    color: "#0b0d0e",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    icon: "SiDigitalocean",
    category: "devops",
    color: "#0080ff",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    icon: "SiGithubactions",
    category: "devops",
    color: "#2088ff",
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "SiGitlab",
    category: "devops",
    color: "#fc6d26",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    icon: "SiJenkins",
    category: "devops",
    color: "#d24939",
  },
  {
    id: "terraform",
    name: "Terraform",
    icon: "SiTerraform",
    category: "devops",
    color: "#7b42bc",
  },
  {
    id: "nginx",
    name: "Nginx",
    icon: "SiNginx",
    category: "devops",
    color: "#009639",
  },
  {
    id: "linux",
    name: "Linux",
    icon: "SiLinux",
    category: "devops",
    color: "#fcc624",
  },
  {
    id: "git",
    name: "Git",
    icon: "SiGit",
    category: "devops",
    color: "#f05032",
  },

  {
    id: "react-native",
    name: "React Native",
    icon: "SiReact",
    category: "mobile",
    color: "#61dafb",
  },
  {
    id: "expo",
    name: "Expo",
    icon: "SiExpo",
    category: "mobile",
    color: "#000020",
  },
  {
    id: "flutter",
    name: "Flutter",
    icon: "SiFlutter",
    category: "mobile",
    color: "#02569b",
  },
  {
    id: "ionic",
    name: "Ionic",
    icon: "SiIonic",
    category: "mobile",
    color: "#3880ff",
  },
  {
    id: "capacitor",
    name: "Capacitor",
    icon: "SiCapacitor",
    category: "mobile",
    color: "#119eff",
  },
  {
    id: "android",
    name: "Android",
    icon: "SiAndroid",
    category: "mobile",
    color: "#3ddc84",
  },
  {
    id: "ios",
    name: "iOS",
    icon: "SiApple",
    category: "mobile",
    color: "#000000",
  },
  {
    id: "pwa",
    name: "PWA",
    icon: "SiPwa",
    category: "mobile",
    color: "#5a0fc8",
  },

  {
    id: "jest",
    name: "Jest",
    icon: "SiJest",
    category: "testing",
    color: "#c21325",
  },
  {
    id: "vitest",
    name: "Vitest",
    icon: "SiVitest",
    category: "testing",
    color: "#6e9f18",
  },
  {
    id: "playwright",
    name: "Playwright",
    icon: "SiPlaywright",
    category: "testing",
    color: "#2ead33",
  },
  {
    id: "cypress",
    name: "Cypress",
    icon: "SiCypress",
    category: "testing",
    color: "#17202c",
  },
  {
    id: "testing-library",
    name: "Testing Library",
    icon: "SiTestinglibrary",
    category: "testing",
    color: "#e33332",
  },
  {
    id: "selenium",
    name: "Selenium",
    icon: "SiSelenium",
    category: "testing",
    color: "#43b02a",
  },
  {
    id: "pytest",
    name: "Pytest",
    icon: "SiPytest",
    category: "testing",
    color: "#0a9edc",
  },

  {
    id: "figma",
    name: "Figma",
    icon: "SiFigma",
    category: "design",
    color: "#f24e1e",
  },
  {
    id: "adobe-xd",
    name: "Adobe XD",
    icon: "SiAdobexd",
    category: "design",
    color: "#ff61f6",
  },
  {
    id: "sketch",
    name: "Sketch",
    icon: "SiSketch",
    category: "design",
    color: "#f7b500",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    icon: "SiAdobephotoshop",
    category: "design",
    color: "#31a8ff",
  },
  {
    id: "illustrator",
    name: "Illustrator",
    icon: "SiAdobeillustrator",
    category: "design",
    color: "#ff9a00",
  },
  {
    id: "blender",
    name: "Blender",
    icon: "SiBlender",
    category: "design",
    color: "#f5792a",
  },
  {
    id: "canva",
    name: "Canva",
    icon: "SiCanva",
    category: "design",
    color: "#00c4cc",
  },

  {
    id: "openai",
    name: "OpenAI",
    icon: "SiOpenai",
    category: "ai",
    color: "#412991",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    icon: "SiAnthropic",
    category: "ai",
    color: "#d4a574",
  },
  {
    id: "langchain",
    name: "LangChain",
    icon: "SiLangchain",
    category: "ai",
    color: "#1c3c3c",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    icon: "SiTensorflow",
    category: "ai",
    color: "#ff6f00",
  },
  {
    id: "pytorch",
    name: "PyTorch",
    icon: "SiPytorch",
    category: "ai",
    color: "#ee4c2c",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    icon: "SiHuggingface",
    category: "ai",
    color: "#ffd21e",
  },
  {
    id: "scikit-learn",
    name: "Scikit-learn",
    icon: "SiScikitlearn",
    category: "ai",
    color: "#f7931e",
  },
  {
    id: "opencv",
    name: "OpenCV",
    icon: "SiOpencv",
    category: "ai",
    color: "#5c3ee8",
  },

  {
    id: "stripe",
    name: "Stripe",
    icon: "SiStripe",
    category: "other",
    color: "#008cdd",
  },
  {
    id: "clerk",
    name: "Clerk",
    icon: "SiClerk",
    category: "other",
    color: "#6c47ff",
  },
  {
    id: "auth0",
    name: "Auth0",
    icon: "SiAuth0",
    category: "other",
    color: "#eb5424",
  },
  {
    id: "sentry",
    name: "Sentry",
    icon: "SiSentry",
    category: "other",
    color: "#362d59",
  },
  {
    id: "twilio",
    name: "Twilio",
    icon: "SiTwilio",
    category: "other",
    color: "#f22f46",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    icon: "SiSendgrid",
    category: "other",
    color: "#1a82e2",
  },
  {
    id: "contentful",
    name: "Contentful",
    icon: "SiContentful",
    category: "other",
    color: "#2478cc",
  },
  {
    id: "sanity",
    name: "Sanity",
    icon: "SiSanity",
    category: "other",
    color: "#f03e2f",
  },
  {
    id: "wordpress",
    name: "WordPress",
    icon: "SiWordpress",
    category: "other",
    color: "#21759b",
  },
  {
    id: "shopify",
    name: "Shopify",
    icon: "SiShopify",
    category: "other",
    color: "#7ab55c",
  },
  {
    id: "webpack",
    name: "Webpack",
    icon: "SiWebpack",
    category: "other",
    color: "#8dd6f9",
  },
  {
    id: "vite",
    name: "Vite",
    icon: "SiVite",
    category: "other",
    color: "#646cff",
  },
  {
    id: "turbo",
    name: "Turborepo",
    icon: "SiTurborepo",
    category: "other",
    color: "#ef4444",
  },
  {
    id: "pnpm",
    name: "pnpm",
    icon: "SiPnpm",
    category: "other",
    color: "#f69220",
  },
  {
    id: "npm",
    name: "npm",
    icon: "SiNpm",
    category: "other",
    color: "#cb3837",
  },
  {
    id: "yarn",
    name: "Yarn",
    icon: "SiYarn",
    category: "other",
    color: "#2c8ebb",
  },
  {
    id: "bun",
    name: "Bun",
    icon: "SiBun",
    category: "other",
    color: "#fbf0df",
  },
  {
    id: "eslint",
    name: "ESLint",
    icon: "SiEslint",
    category: "other",
    color: "#4b32c3",
  },
  {
    id: "prettier",
    name: "Prettier",
    icon: "SiPrettier",
    category: "other",
    color: "#f7b93e",
  },
  {
    id: "zod",
    name: "Zod",
    icon: "SiZod",
    category: "other",
    color: "#3068b7",
  },
  {
    id: "markdown",
    name: "Markdown",
    icon: "SiMarkdown",
    category: "other",
    color: "#000000",
  },
];

export function getTechById(id: string): Technology | undefined {
  return TECHNOLOGIES.find((t) => t.id === id);
}

export function getTechsByCategory(category: TechCategory): Technology[] {
  return TECHNOLOGIES.filter((t) => t.category === category);
}

export function getTechsByIds(ids: string[]): Technology[] {
  return ids
    .map((id) => getTechById(id))
    .filter((t): t is Technology => t !== undefined);
}

export function searchTechnologies(query: string): Technology[] {
  const q = query.toLowerCase();
  return TECHNOLOGIES.filter(
    (t) => t.name.toLowerCase().includes(q) || t.id.toLowerCase().includes(q)
  );
}
