'use client';

import {
    SiTypescript,
    SiJavascript,
    SiPython,
    SiRust,
    SiGo,
    SiSharp,
    SiCplusplus,
    SiPhp,
    SiRuby,
    SiSwift,
    SiKotlin,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiNuxtdotjs,
    SiAngular,
    SiSvelte,
    SiAstro,
    SiRemix,
    SiTailwindcss,
    SiSass,
    SiCss3,
    SiHtml5,
    SiRedux,
    SiFramer,
    SiGreensock,
    SiThreedotjs,
    SiShadcnui,
    SiRadixui,
    SiChakraui,
    SiMui,
    SiAntdesign,
    SiStorybook,
    SiNodedotjs,
    SiExpress,
    SiFastify,
    SiNestjs,
    SiDjango,
    SiFastapi,
    SiFlask,
    SiRubyonrails,
    SiLaravel,
    SiDotnet,
    SiSpring,
    SiGraphql,
    SiTrpc,
    SiPrisma,
    SiDrizzle,
    SiSocketdotio,
    SiPostgresql,
    SiMysql,
    SiMongodb,
    SiRedis,
    SiSqlite,
    SiSupabase,
    SiFirebase,
    SiPlanetscale,
    SiNexon,
    SiElasticsearch,
    SiAmazondynamodb,
    SiDocker,
    SiKubernetes,
    SiAmazonwebservices,
    SiGooglecloud,
    SiVercel,
    SiNetlify,
    SiCloudflare,
    SiRailway,
    SiDigitalocean,
    SiGithubactions,
    SiGitlab,
    SiJenkins,
    SiTerraform,
    SiNginx,
    SiLinux,
    SiGit,
    SiExpo,
    SiFlutter,
    SiIonic,
    SiCapacitor,
    SiAndroid,
    SiApple,
    SiPwa,
    SiJest,
    SiVitest,
    SiCypress,
    SiTestinglibrary,
    SiSelenium,
    SiPytest,
    SiFigma,
    SiAdobexd,
    SiSketch,
    SiAdobephotoshop,
    SiAdobeillustrator,
    SiBlender,
    SiCanva,
    SiOpenai,
    SiAnthropic,
    SiLangchain,
    SiTensorflow,
    SiPytorch,
    SiHuggingface,
    SiScikitlearn,
    SiOpencv,
    SiStripe,
    SiClerk,
    SiAuth0,
    SiSentry,
    SiTwilio,
    SiSendgrid,
    SiContentful,
    SiSanity,
    SiWordpress,
    SiShopify,
    SiWebpack,
    SiVite,
    SiTurborepo,
    SiPnpm,
    SiNpm,
    SiYarn,
    SiBun,
    SiEslint,
    SiPrettier,
    SiZod,
    SiMarkdown,
} from 'react-icons/si';
import { FaJava } from 'react-icons/fa';
import { useTheme } from '@/components/theme/ThemeProvider';

const ICON_MAP: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
    SiTypescript,
    SiJavascript,
    SiPython,
    SiRust,
    SiGo,
    FaJava,
    SiSharp,
    SiCplusplus,
    SiPhp,
    SiRuby,
    SiSwift,
    SiKotlin,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiNuxtdotjs,
    SiAngular,
    SiSvelte,
    SiAstro,
    SiRemix,
    SiTailwindcss,
    SiSass,
    SiCss3,
    SiHtml5,
    SiRedux,
    SiFramer,
    SiGreensock,
    SiThreedotjs,
    SiShadcnui,
    SiRadixui,
    SiChakraui,
    SiMui,
    SiAntdesign,
    SiStorybook,
    SiNodedotjs,
    SiExpress,
    SiFastify,
    SiNestjs,
    SiDjango,
    SiFastapi,
    SiFlask,
    SiRubyonrails,
    SiLaravel,
    SiDotnet,
    SiSpring,
    SiGraphql,
    SiTrpc,
    SiPrisma,
    SiDrizzle,
    SiSocketdotio,
    SiPostgresql,
    SiMysql,
    SiMongodb,
    SiRedis,
    SiSqlite,
    SiSupabase,
    SiFirebase,
    SiPlanetscale,
    SiNexon,
    SiElasticsearch,
    SiAmazondynamodb,
    SiDocker,
    SiKubernetes,
    SiAmazonwebservices,
    SiGooglecloud,
    SiVercel,
    SiNetlify,
    SiCloudflare,
    SiRailway,
    SiDigitalocean,
    SiGithubactions,
    SiGitlab,
    SiJenkins,
    SiTerraform,
    SiNginx,
    SiLinux,
    SiGit,
    SiExpo,
    SiFlutter,
    SiIonic,
    SiCapacitor,
    SiAndroid,
    SiApple,
    SiPwa,
    SiJest,
    SiVitest,
    SiCypress,
    SiTestinglibrary,
    SiSelenium,
    SiPytest,
    SiFigma,
    SiAdobexd,
    SiSketch,
    SiAdobephotoshop,
    SiAdobeillustrator,
    SiBlender,
    SiCanva,
    SiOpenai,
    SiAnthropic,
    SiLangchain,
    SiTensorflow,
    SiPytorch,
    SiHuggingface,
    SiScikitlearn,
    SiOpencv,
    SiStripe,
    SiClerk,
    SiAuth0,
    SiSentry,
    SiTwilio,
    SiSendgrid,
    SiContentful,
    SiSanity,
    SiWordpress,
    SiShopify,
    SiWebpack,
    SiVite,
    SiTurborepo,
    SiPnpm,
    SiNpm,
    SiYarn,
    SiBun,
    SiEslint,
    SiPrettier,
    SiZod,
    SiMarkdown,
};

interface Technology {
    id: string;
    name: string;
    icon: string;
    category: string;
    color?: string;
}

interface TechBadgeProps {
    tech: Technology;
    size?: 'sm' | 'md';
}

export default function TechBadge({ tech, size = 'md' }: TechBadgeProps) {
    const { theme } = useTheme();
    const isDark = theme === 'dark';

    const Icon = ICON_MAP[tech.icon];
    const color = tech.color || '#6b7280';

    const sizeClasses = {
        sm: 'px-2 py-1 text-[10px] gap-1.5',
        md: 'px-3 py-1.5 text-xs gap-2',
    };

    const iconSizes = {
        sm: 'w-3 h-3',
        md: 'w-3.5 h-3.5',
    };

    return (
        <span
            className={`inline-flex items-center rounded-lg font-medium border transition-all duration-200 hover:scale-105 ${sizeClasses[size]}`}
            style={{
                backgroundColor: isDark ? `${color}15` : `${color}10`,
                borderColor: isDark ? `${color}30` : `${color}25`,
                color: isDark ? color : color,
            }}
        >
            {Icon && (
                <Icon
                    className={iconSizes[size]}
                    style={{ color }}
                />
            )}
            <span style={{ color: isDark ? '#e2e8f0' : '#334155' }}>
                {tech.name}
            </span>
        </span>
    );
}

export function getTechIcon(iconName: string): React.ComponentType<{ className?: string; style?: React.CSSProperties }> | null {
    return ICON_MAP[iconName] || null;
}